receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

processors:
  transform/strip_session:
    error_mode: ignore
    metric_statements:
      - context: datapoint
        statements:
          - delete_key(attributes, "session_id")
  deltatocumulative:
    max_stale: 48h

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
    metric_expiration: 720h
  otlp_http:
    endpoint: http://tempo:4318

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [transform/strip_session, deltatocumulative]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      exporters: [otlp_http]
